name: Deploy spec to docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: gweicz/utxo22-docs
          ref: master
          path: docs
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run --allow-read --allow-write scripts/update-docs.js
      - uses: stefanzweifel/git-auto-commit-action@v2.3.0
        working-directory: ./docs
        with:
          commit_message: Specs update
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

