name: Update Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: gweicz/utxo22-docs
          ref: master
          path: docs
          token: ${{ secrets.TOKEN_DOCS }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: make docs-update
      - uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          repository: ./docs
          commit_message: Specs update
          branch: master
